server {
    listen 80;
    server_name ultimatemove.co.uk www.ultimatemove.co.uk;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ultimatemove.co.uk www.ultimatemove.co.uk;

    ssl_certificate     /etc/letsencrypt/live/ultimatemove.co.uk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ultimatemove.co.uk/privkey.pem;

    location /api/ {
        proxy_pass http://expense-tracker:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://umet-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
